### ISSUE TITLE
Cannot read property 'clientWidth' of null

### ISSUE THREAD

**Issue by ramnathv** [DarkMarmot/kodama#1]
I am trying to just reproduce your example on jsfiddle, but running into errors. Here is a link to the fiddle for reproducing the error

http://jsfiddle.net/ramnathv/zk4jq37m/

**Comment by DarkMarmot** [comment]
Ahh, thanks for checking it out and trying it! I see what's happening... it's trying to select the 'body' node when the script runs -- but apparently it's not available via jsfiddle when the script is executed as a dependency. I think I need to add a handler to wait for the dom to be ready -- and/or add a method to let you initialize the tooltip so that it builds above the dom node of your choice.

I'll try to get a fix out soon! Thanks again!,
Scott

**Comment by ramnathv** [comment]
Great. Thanks for a great library.

**Comment by DarkMarmot** [comment]
Thanks! I'm excited to have my first 'issue' reported :) I've released a new version with checks for DOMContentLoaded -- the fiddle you posted looks like it works now after I refreshed it.

**Comment by ramnathv** [comment]
Great! Works beautifully. Thanks!
